# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'hello.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\"\x1b\n\x0bPingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tPongReply\x12\x0f\n\x07message\x18\x01 \x01(\t28\n\x0fPingPongService\x12%\n\x07SayPong\x12\x0c.PingRequest\x1a\n.PongReply\"\x00\x42\x38\n%org.springframework.grpc.sample.protoB\rPingPongProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%org.springframework.grpc.sample.protoB\rPingPongProtoP\001'
  _globals['_PINGREQUEST']._serialized_start=15
  _globals['_PINGREQUEST']._serialized_end=42
  _globals['_PONGREPLY']._serialized_start=44
  _globals['_PONGREPLY']._serialized_end=72
  _globals['_PINGPONGSERVICE']._serialized_start=74
  _globals['_PINGPONGSERVICE']._serialized_end=130
# @@protoc_insertion_point(module_scope)
